version: '3.8'
services:
  web:
    image: nginx:stable-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/app.conf
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_USER=${DB_ROOT_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./app:/app
      - ./custom.php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - web
      - mysql

volumes:
  mysql_data: { }
